version: v1
name: wf-quality-customer
type: workflow
tags:
  - demo.customer
description: The job performs metrics calculations and checks on customer data
workflow:
  title: Metrics and checks
  dag:
    - name: quality-customer
      title: Metrics and checks
      description: The job performs metrics calculations and checks on customer data
      spec:
        stack: flare:3.0
        compute: runnable-default
        tags:
          - Metrics
        title: Metrics and checks
        description: The job performs metrics calculations and checks on customer data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: source
                dataset:  dataos://postgres:retail_accelerator/customer
                format: jdbc
                options: 
                  driver: org.postgresql.Driver

            assertions:
              - column: customer_id
                tests:
                  - duplicate_count == 0
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: phone_number
                validFormat:
                  regex: ^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$
                tests:
                  - duplicate_count == 0
                  - missing_percentage == 0
                  - missing_count == 0

              - column: email_id
                validFormat:
                  regex: ([-!#-'*+/-9=?A-Z^-~]+(\.[-!#-'*+/-9=?A-Z^-~]+)*|"([]!#-[^-~ \t]|(\\[\t -~]))+")@([-!#-'*+/-9=?A-Z^-~]+(\.[-!#-'*+/-9=?A-Z^-~]+)*|\[[\t -Z^-~]*])
                tests: 
                  - duplicate_count == 0
                  - missing_percentage == 0
                  - missing_count == 0

              - column: age
                validFormat:
                  regex: ^[1-9]+[0-9]*$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: gender
                validFormat:
                  regex: (?:'MALE'|'FEMALE')
                tests:
                  - missing_count <= 0

              - column: last_name
                validFormat:
                  regex: ^[a-zA-Z]
                tests:
                  - missing_count == 0

              - column: first_name
                validFormat:
                  regex: ^[a-zA-Z]
                tests:
                  - missing_count == 0

              - column: education_level
                validFormat:
                  regex: ^[a-zA-Z][0-9a-zA-Z .,'-]*$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: marital_status
                validFormat:
                  regex: ^[a-zA-Z][0-9a-zA-Z .,'-]*$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: country
                validFormat:
                  regex: ^[a-zA-Z]
                tests: 
                  - missing_percentage == 0
                  - missing_count <= 0
            
              - column: state
                validFormat:
                  regex: ^[a-zA-Z]
                tests: 
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: city
                validFormat:
                  regex: ^[a-zA-Z]
                tests: 
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: annual_income
                validFormat:
                  regex: ^[a-zA-Z0-9_.-]*$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: number_of_children
                validFormat: 
                  regex: ^[1-9]+[0-9]*$
                tests: 
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: phone_number
                validFormat:
                  regex: ^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$
                tests:
                  - duplicate_count == 0
                  - missing_percentage == 0
                  - missing_count == 0  

              - column: birth_date
                validFormat:
                  regex: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: zip_code
                validFormat:
                  regex: ^[a-zA-Z0-9 ]*$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: social_class
                validFormat:
                  regex: ^[a-zA-Z]
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: birth_date
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: marital_status
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: degree_of_loyalty
                validFormat:
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: hobbies
                validFormat:
                  regex: ^[a-zA-Z]
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: annual_income
                validFormat:
                  regex: ^[a-zA-Z0-9 ]*$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: occupation
                validFormat:
                  regex: ^[a-zA-Z0-9 ]*$
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: register_date
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: mailing_street
                validFormat:
                tests:
                  - missing_percentage == 0
                  - missing_count <= 0
