version: v1
name: wf-quality-prod-category
type: workflow
tags:
  - demo.category
description: The job performs metrics calculations and checks on product_category data
workflow:
  title: Metrics and checks
  dag:
    - name: quality-product-category
      title: Metrics and checks
      description: The job performs metrics calculations and checks on product_category data
      spec:
        stack: flare:3.0
        compute: runnable-default
        tags:
          - Metrics
        title: Metrics and checks
        description: The job performs metrics calculations and checks on product_category data
        flare:
          job:
            explain: true
            logLevel: INFO
            inputs:
              - name: source
                dataset:  dataos://postgres:retail_accelerator/product_category
                format: jdbc
                options: 
                  driver: org.postgresql.Driver
                  
            assertions:
              - column: product_category
                validFormat:
                  regex: /[a-zA-Z]+/g
                tests:
                  - duplicate_count == 0
                  - missing_percentage == 0
                  - missing_count <= 0

              - column: product_category_id
                validFormat:
                  regex: ^[a-zA-Z0-9_.-]*$
                tests:
                  - duplicate_count == 0
                  - missing_percentage == 0
                  - missing_count <= 0