# Generated by Django 2.2.14 on 2023-05-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230502_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dummy_variable',
        ),
    ]
