# Generated by Django 2.2.14 on 2023-05-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_dummy_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
