version: v1
name: wf-orderline-profile
type: workflow
tags:
  - demo.orderline
workflow:
  title: Connect orderline
  dag:
  - name: orderline-profile-profile
    title: orderline profile Profiler
    description: The job performs profiling on the order line item data
    spec:
      stack: flare:3.0
      compute: runnable-default
      tier: system
      title: order Profiler
      persistentVolume:
        name: persistent-v
        directory: fides
      flare:
        driver:
          coreLimit: 1100m
          cores: 1
          memory: 1048m
        executor:
          coreLimit: 1200m
          cores: 1
          instances: 1
          memory: 1000m 
        job:
          explain: true
          inputs:
            - name: order
              dataset:  dataos://postgres:retail_accelerator/order_line_item
              format: jdbc
              options: 
                driver: org.postgresql.Driver
          logLevel: INFO
          profile:
            level: basic
