version: v1
name: wf-transaction-profile
type: workflow
tags:
  - demo.transaction
workflow:
  title: Connect transaction
  dag:
  - name: transaction-profile-profile
    title: transaction profile Profiler
    description: The job performs profiling on the transaction data
    spec:
      stack: flare:3.0
      compute: runnable-default
      tier: system
      title: transaction Profiler
      persistentVolume:
        name: persistent-v
        directory: fides
      flare:
        driver:
          coreLimit: 1100m
          cores: 1
          memory: 1048m
        executor:
          coreLimit: 1200m
          cores: 1
          instances: 1
          memory: 1000m 
        job:
          explain: true
          inputs:
            - name: transaction
              dataset:  dataos://postgres:retail_accelerator/transaction
              format: jdbc
              options: 
                driver: org.postgresql.Driver
          logLevel: INFO
          profile:
            level: basic
