version: v1
name: wf-order-profile
type: workflow
tags:
  - demo.order
workflow:
  title: Connect order
  dag:
  - name: order-profile-profile
    title: order profile Profiler
    description: The job performs profiling on the order data
    spec:
      stack: flare:3.0
      compute: runnable-default
      tier: system
      title: order Profiler
      persistentVolume:
        name: persistent-v
        directory: fides
      flare:
        driver:
          coreLimit: 1100m
          cores: 1
          memory: 1048m
        executor:
          coreLimit: 1200m
          cores: 1
          instances: 1
          memory: 1000m 
        job:
          explain: true
          inputs:
            - name: orders
              dataset:  dataos://postgres:retail_accelerator/orders
              format: jdbc
              options: 
                driver: org.postgresql.Driver
          logLevel: INFO
          profile:
            level: basic
