version: v1
name: wf-customer-profile
type: workflow
tags:
  - demo.customer
workflow:
  title: Connect customers
  dag:
  - name: customer-profile-profile
    title: customer profile Profiler
    description: The job performs profiling on the customer data
    spec:
      stack: flare:3.0
      compute: runnable-default
      tier: system
      title: customer Profiler
      persistentVolume:
        name: persistent-v
        directory: fides
      flare:
        driver:
          coreLimit: 1100m
          cores: 1
          memory: 1048m
        executor:
          coreLimit: 1200m
          cores: 1
          instances: 1
          memory: 1000m 
        job:
          explain: true
          inputs:
            - name: customer
              dataset:  dataos://postgres:retail_accelerator/customer
              format: jdbc
              options: 
                driver: org.postgresql.Driver
          logLevel: INFO
          profile:
            level: basic