version: v1
name: wf-customer
type: workflow
tags:
  - demo.customer
description: The job ingests retail customer data from Blob Storage to postgres
workflow:
  title: Connect retail customer
  dag:
    - name: retail-customer
      title: retail-customer Dataset
      spec:
        tags:
          - demo.customer
        stack: flare:3.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 1100m
            cores: 1
            memory: 1048m
          executor:
            coreLimit: 1200m
            cores: 1
            instances: 1
            memory: 1000m 
          job:
            explain: true

            inputs:
              - name: customer
                dataset: dataos://thirdparty01:analytics/retail_accelerator/customer/customer.csv?acl=rw                
                format: csv
            logLevel: INFO
            outputs:
              - name: final
                dataset: dataos://postgres:retail_accelerator/customer?acl=rw 
                driver: org.postgresql.Driver
                format: jdbc

                description: This dataset gives you details of all retail customer and their corresponding attributes.
                tags:
                  - demo.customer
                options:
                  saveMode: overwrite

                title: retail customer Source Data
            steps:
              - sequence:
                  - name: final
                    sql: select * from customer
                    functions:
                       - name: any_timestamp
                         column: birth_date
                         asColumn: birth_date

                       - name: any_timestamp
                         column: register_date
                         asColumn: register_date

                       - name: drop_duplicates 
                         columns: 
                          - customer_id

                       - name: set_type
                         columns:
                          first_name: string
                          last_name: string
                          gender: string
                          phone_number: string
                          email_id: string
                          age: int
                          education_level: string
                          marital_status: string
                          number_of_children: int
                          occupation: string
                          annual_income: string
                          hobbies: string
                          degree_of_loyalty: string
                          social_class: string
                          mailing_street: string
                          city: string
                          state: string
                          country: string
                          zip_code: string

                  
                       - name: snake_case
                       - name: change_column_case
                         case: lower
#                   
#- name: dt-retail-transaction
#  spec:
#    stack: toolbox
#    compute: runnable-default
#    toolbox:
#      dataset: dataos://postgres:public/transaction?acl=rw
#      action:
#        name: set_version
#        value: latest
#  dependencies:
 #       - retail-transaction