version: v1
name: wf-event-trigger
type: workflow
workspace: public
description:  The Job Ingests event stream data from bigquery
tags:
  - dataos.eventstream
workflow:
  title: event trigger data
  schedule:                         
    cron: "*/1 * * * *"
    concurrencyPolicy: Forbid 
  dag:
    - name: event-stream
      title: event stream data
      description: This job ingest data of event stream from BQ to icebasedev
      spec:
        tags:
          - dataos.eventstream
        stack: flare:3.0
        compute: runnable-default
        flare:
            driver:
                coreLimit: 1200m
                cores: 1
                memory: 1024m
            executor:
                coreLimit: 1200m    
                cores: 1
                instances: 1
                memory: 1024m
            job:
              explain: true
              streaming:
                batchMode: true
                triggerMode: Once
                checkpointLocation: dataos://icebase:sys01/checkpoint/event/test/event-stream-001?acl=rw
              inputs:
                - name: event_input
                  dataset: dataos://retailevents:analytics_373787125/events_intraday_20230511
                  incremental:
                  context: incremental_data
                  sql: select *  from incremental_data where  event_timestamp   > to_timestamp('$|start_time|') and order.created_on <= '$|end_time|'
                  keys:
                    - name: start_time
                      sql: SELECT "2023-01-01 00:00:00"
                                                                                
                    - name: end_time
                      sql: select current_timestamp()
                  state:
                    - key: start_time
                      value: end_time
              logLevel: INFO
              outputs:
                - name: eventstream
                  dataset: dataos://icebasedev:retail_accelerator/ga_test?acl=rw
                  format: Iceberg
                  description: Test sample GA sessions data for retail accelerator
                  tags:
                    - demo.customers
                  options:
                        saveMode: append
                        iceberg:
                          # partitionSpec:
                          #   - type: identity
                          #     column: event_name
                          #   - type: month
                          #     column: event_date
                          #     name: month_partitioned
                          properties:
                            write.format.default: parquet
                            write.metadata.compression-codec: gzip
                  title: retail customers Source Data
              steps:
                  - sequence:
                    - name: eventstream
                      sql: >
                        select * from event_input
                      functions:
                        - name: snake_case
                        - name: change_column_case
                          case: lower
                        - name: any_timestamp
                          column: event_timestamp
                          asColumn: event_timestamp
                        # - name: any_timestamp
                        #   column: event_date
                        #   asColumn: event_date
    - name: dataos-tool-eventstream
      spec:
        stack: toolbox
        compute: runnable-default
        toolbox:
          dataset: dataos://icebasedev:retail_accelerator/ga_test?acl=rw
          action:
            name: set_version
            value: latest
      dependencies:
        - event-stream