version: v1
name: wf-product-subcat
type: workflow
tags:
  - demo.subcategory
description: The job ingests retail product subcategory data from Blob Storage to postgres
workflow:
  title: Connect retail product-subcategory
  dag:
    - name: retail-product-subcategory
      title: retail-product-subcategory Dataset
      spec:
        tags:
          - demo.product-subcategory
        stack: flare:3.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 1100m
            cores: 1
            memory: 1048m
          executor:
            coreLimit: 1200m
            cores: 1
            instances: 1
            memory: 1000m 
          job:
            explain: true

            inputs:
              - name: product_subcategory
                dataset: dataos://thirdparty01:analytics/retail_accelerator/product/product_subcategory.csv?acl=rw           
                format: csv
            logLevel: INFO
            outputs:
              - name: final
                dataset: dataos://postgres:retail_accelerator/subcategory?acl=rw 
                driver: org.postgresql.Driver
                format: jdbc

                description: This dataset gives you details of all retail product_subcategory and their corresponding attributes.
                tags:
                  - demo.product_subcategory
                options:
                  saveMode: overwrite

                title: retail product_subcategory Source Data
            steps:
              - sequence:
                  - name: final
                    sql: select * from product_subcategory
                    functions:

                       - name: set_type
                         columns:
                          product_subcategory: string
                          product_subcategory_id: string
                          product_category_id: string
                  
                       - name: snake_case
                       - name: change_column_case
                         case: lower
#                   
#- name: dt-retail-transaction
#  spec:
#    stack: toolbox
#    compute: runnable-default
#    toolbox:
#      dataset: dataos://postgres:public/transaction?acl=rw
#      action:
#        name: set_version
#        value: latest
#  dependencies:
 #       - retail-transaction