version: v1
name: wf-product-category
type: workflow
tags:
  - demo.category
description: The job ingests retail product category data from Blob Storage to postgres
workflow:
  title: Connect retail product-category
  dag:
    - name: retail-product-category
      title: retail-product-category Dataset
      spec:
        tags:
          - demo.product-category
        stack: flare:3.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 1100m
            cores: 1
            memory: 1048m
          executor:
            coreLimit: 1200m
            cores: 1
            instances: 1
            memory: 1000m 
          job:
            explain: true

            inputs:
              - name: product_category
                dataset: dataos://thirdparty01:analytics/retail_accelerator/product/product_category.csv?acl=rw         
                format: csv
            logLevel: INFO
            outputs:
              - name: final
                dataset: dataos://postgres:retail_accelerator/product_category?acl=rw 
                driver: org.postgresql.Driver
                format: jdbc

                description: This dataset gives you details of all retail product_category and their corresponding attributes.
                tags:
                  - demo.product_category
                options:
                  saveMode: overwrite

                title: retail product_category Source Data
            steps:
              - sequence:
                  - name: final
                    sql: select * from product_category
                    functions:

                       - name: set_type
                         columns:
                          product_category: string
                          product_category_id: string
                  
                       - name: snake_case
                       - name: change_column_case
                         case: lower