version: v1
name: wf-order
type: workflow
tags: 
  - demo.order
description: The job ingests retail order data from Blob Storage to postgres
workflow: 
  title: Connect retail order
  dag:
    - name: retail-order
      title: retail-order Dataset
      spec:
        tags:
          - demo.order
        stack: flare:3.0
        compute: runnable-default
        flare:
          driver: 
            coreLimit: 1100m
            cores: 1
            memory: 1048m
          executor:
            coreLimit: 1200m
            cores: 1
            instances: 1
            memory: 1000m 
          job:
            explain: true

            inputs:
              - name: order
                dataset: dataos://thirdparty01:analytics/retail_accelerator/order/order.csv?acl=rw                
                format: csv
            logLevel: INFO
            outputs: 
              - name: final
                dataset: dataos://postgres:retail_accelerator/orders?acl=rw
                driver: org.postgresql.Driver
                format: jdbc

                description: This dataset gives you details of all retail order and their corresponding attributes.
                tags:
                  - demo.order
                options:
                  saveMode: overwrite

                title: retail order Source Data
            steps: 
              - sequence: 
                  - name: final
                    sql: select * from order
                    functions: 
                       - name: any_timestamp
                         column: order_date
                         asColumn: order_date

                       - name: drop_duplicates 
                         columns: 
                          - order_id