version: v1
name: wf-orderline
type: workflow
tags:
  - demo.orderline
description: The job ingests retail order_line_item data from Blob Storage to postgres
workflow:
  title: Connect retail order_line_item
  dag:
    - name: retail-orderline
      title: retail-orderline Dataset
      spec:
        tags:
          - demo.orderline
        stack: flare:3.0
        compute: runnable-default
        flare:
          driver:
            coreLimit: 1100m
            cores: 1
            memory: 1048m
          executor:
            coreLimit: 1200m
            cores: 1
            instances: 1
            memory: 1000m 
          job:
            explain: true

            inputs:
              - name: orderline
                dataset: dataos://thirdparty01:analytics/retail_accelerator/order/order_line_item.csv?acl=rw                
                format: csv
            logLevel: INFO
            outputs:
              - name: final
                dataset: dataos://postgres:retail_accelerator/order_line_item?acl=rw 
                driver: org.postgresql.Driver
                format: jdbc

                description: This dataset gives you details of all retail order_line_item and their corresponding attributes.
                tags:
                  - demo.orderline
                options:
                  saveMode: overwrite

                title: retail order_line_item Source Data
            steps:
              - sequence:
                  - name: final
                    sql: select * from orderline
                    functions:
                       - name: drop_duplicates 
                         columns: 
                          - order_id
  
                       - name: set_type
                         columns: 
                          product_price: float
                          order_total: float
                          discounted_amount: float
                          tax_percentage: float
                          shipping_amount: int
                          total_price: float
                      
                       - name: snake_case
                       - name: change_column_case
                         case: lower
#                   
#- name: dt-retail-transaction
#  spec:
#    stack: toolbox
#    compute: runnable-default
#    toolbox:
#      dataset: dataos://postgres:public/transaction?acl=rw
#      action:
#        name: set_version
#        value: latest
#  dependencies:
 #       - retail-transaction